syntax = "proto3";

package cleanddd.employees.v1;
import "google/api/annotations.proto";
option csharp_namespace = "CleanDDD.Contracts.Employees.v1";

service EmployeeService {
  rpc GetEmployee (GetEmployeeRequest) returns (GetEmployeeResponse)
  {
      option (google.api.http) = {
        get: "/v1/employees/{id}"
      };
  }
  rpc GetEmployees (GetEmployeesRequest) returns (GetEmployeesResponse)
  {
      option (google.api.http) = {
          get: "/v1/employees"
      };
  }
  rpc GetEmployeeByEmail (GetEmployeeByEmailRequest) returns (GetEmployeeByEmailResponse)
  {
      option (google.api.http) = {
          get: "/v1/employees:byEmail"
          additional_bindings {
              get: "/v1/employees/byEmail"
          }
      };
  }
}

// Queries
message GetEmployeeRequest { string id = 1; }
message GetEmployeeResponse { Employee employee = 1; }

message GetEmployeesRequest { }
message GetEmployeesResponse { repeated Employee items = 1;}

message GetEmployeeByEmailRequest { string email = 1; }
message GetEmployeeByEmailResponse { Employee employee = 1; }

// View
message Employee {
  string id = 1;
  string name    = 2;
  string email   = 3;
  bool   is_active = 4;
}