<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Grpc\Channels\" />
    <Folder Include="Grpc\Clients\" />
    <Folder Include="Auth\" />
    <Folder Include="Mappers\" />
  </ItemGroup>

</Project>
